version = 0.1

[default.deploy.parameters]
stack_name = "cloud-monitor"
resolve_s3 = true
s3_prefix = "cloud-monitor"
capabilities = "CAPABILITY_IAM"
image_repositories = []
confirm_changeset = true
parameter_overrides = "ProjectName=\"cloud-monitor\" NotificationEmail=\"hy12042003@gmail.com\" VpcId=\"vpc-0a10a5fd83f8ed401\" PublicSubnet1=\"subnet-05e03d7ef9f5dc74a\" PublicSubnet2=\"subnet-055db93aa53c699c1\" KeyPairName=\"monitoring-test-key\" SSHLocation=\"0.0.0.0/0\" InstanceType=\"t3.micro\" AmiId=\"/aws/service/ami-amazon-linux-latest/al2023-ami-kernel-6.1-x86_64\" AlbName=\"test-alb\" TargetGroupName=\"test-tg\" AutoScalingGroupName=\"test-asg\" LaunchTemplateName=\"test-lt\" DashboardName=\"test-dashboard\" AlertsTopicName=\"test-topic\" HighCpuAlarmName=\"test-high-alarm\" StatusCheckAlarmName=\"test-status-alarm\" IncidentLogsTableName=\"test-log\" NotificationCooldownTableName=\"test-cooldown\" CpuThreshold=\"70\""

[default.global.parameters]
region = "ap-south-2"
